title: 'Site config'
data:
  site_name: 'Statamic Livewire Filters Demos & Examples'
  description: |-
    In this demo Statamic installation you can check the various
    examples to see what Livewire Filters is able to do.