tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              type: text
              display: 'Site name'
          -
            handle: description
            field:
              character_limit: 160
              type: textarea
              display: Description
